version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: 'pgtest'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spssql

    ports:
      - '5432:5432'
    volumes:
      - ./sps.sql:/docker-entrypoint-initdb.d/sps.sql